### ISSUE TITLE
opt.obj_type -> par.obj_type

### ISSUE THREAD

**Issue by BBallnus** [ICB-DCM/PESTO#48]
Following the discussion from yesterday, I would suggest to shift opt.obj_type into the parameters struct , since it is part of the problem formulation as pointed out by Fabian.

**Comment by JanHasenauer** [comment]
The problem I see with this is that we would have to deplicate it than also into the property struct. I would however try to avoid redundancies. Maybe a separate options struct for the objective function?
(This however does also not feel right as this options struct would be very small and as we would have to include additional inputs for all the functions.)

**Comment by paulstapor** [comment]
As I said yesterday: You would need to pass the parameter struct also to property routines... I'm rather into a new struct like "problem" or something alike for the long term. Changing this right now only for the next 4 weeks does not make sense...

**Comment by dweindl** [comment]
Using something like a `Problem' class which holds information on parameters, properties and objective function (including ```obj_type```) sounds good to me. Some sanity checks could be included directly there, and not in every single other function. That will however require some changes all over the place.

**Comment by paulstapor** [comment]
> That will however require some changes all over the place. I am not sure if I would want to start that right now.

That's what I meant with "the next 4 weeks". That would definitely need more time, since all big routines are involved. Hence this should be done along with defining classes for parameters and properties and a restructuring of the options. I don't want this to happen before the application note is submitted... Who ever is really, really, really eager to do this before I will have the time to start working on it: Use a branch of its own and branch away from feature_lsqnonlin or develop_minibatch and merge in the new develop version first.

**Comment by BBallnus** [comment]
Ok, let's postpone a general rework of the options design. I'm gonna close this issue for now.
