### ISSUE TITLE
Indentation style

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PESTO#50]
Matlab's default indentation scheme is to not indent the first level of code:
```
function [ output_args ] = Untitled2( input_args )
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here
output_args = 1;
end
```

I find that extremely unintuitive and in the case of multiple functions per file, it reduces readability significantly.
Therefore, I would like to indent all levels of code as in:
```
function [ output_args ] = Untitled2( input_args )
    %UNTITLED2 Summary of this function goes here
    %   Detailed explanation goes here
    output_args = 1;
end
```

(This can be done automatically by changing ```Preferences > MATLAB > Editor/Debugger > Language > Indenting``` to ```Indent all functions``` and then in the editor simply choosing ```smart indent``` from the context menu.)

My suggestion would be to use this style for new additions or during major reorganizations only, to not ruining  ```git blame``` output.

Any opinions?

**Comment by paulstapor** [comment]
Definitely agree. To be honest, here I'm not consistent. When I write new code, I usually like to also indent the first level in a function, but in some cases I didn't, since that was more consistent with what already existed...
Let's agree on what you just propose. At least for me (and obviously for Fabien), that's fine.

**Comment by JanHasenauer** [comment]
I also agree!

**Comment by BBallnus** [comment]
Agreed!
