### ISSUE TITLE
reduce number of folders

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/PESTO#79]
Maybe it might be an idea to put PToptions, PHSoptions, MALAoptions, and DRAMoptions all into the SamplingOptions folder?
(just the files, not the folders)

**Comment by dweindl** [comment]
Does Matlab agree with that?

**Comment by paulstapor** [comment]
we have the same in AMICI

**Comment by dweindl** [comment]
But none of those files in @amimodel are classes, or are they?

**Comment by BBallnus** [comment]
I tried. You can't. At least not that I know.

**Comment by BBallnus** [comment]
sorry, my last comment was a bit unspecific. This is what I meant: The PestoSamplingClass has the algorithm classes as sub-classes. Unfortunately, I do not know any convenient way to nest @folders. I have explicitly tinkered at this problem as well. I found a way to initialize with nested @folders within the main class - but the problem is, that you can not access any of the subclass properties from outside (your script), since Matlab does not "see" the subclasses.

**Comment by dweindl** [comment]
Why not ask the Matlab [documentation](https://de.mathworks.com/help/matlab/matlab_oop/organizing-classes-in-folders.html): 
>There are two types of folders that can contain class definition files.

>    Path folders — The folder is on the MATLAB® path and the folder name does not begin with an @ character. Use this type of folder when you want multiple classes in one folder. However, the entire class definition must be contained in one .m file.

>    Class folders — The folder name begins with an @ character followed by the class name. The folder is not on the MATLAB path, but its parent folder is on the path. Use this type of folder when you want to use multiple files for one class definition. 

So it is possible, but I am not sure whether it is a big advantage. I think having all API functions and classes in the top level folder is still fine. Then there is only one folder to be added to the matlab path.

**Comment by BBallnus** [comment]
I think everyone is aware of the MATLAB documentation, which was indeed the first address I accessed when I faced this problem a couple of days ago.

It is NOT possible to access nested @folder routines beyond the first level behind your matlab path without workarrounds I currently don't know. You can't access the subclass properties from your script anymore: E.g. SamplingPestoOptions.PT.nTemps is not accessible anymore. Maybe there is a workaround with some fancy getter and setter routines in the main class - but I think it is not worth the time seeking a different solution, due to the reason Daniel mentioned and simplicity/readability of our code.

**Comment by dweindl** [comment]
> It is NOT possible to access nested @folder routines beyond the first level behind your matlab path without workarrounds I currently don't know.

As I just quoted, the workaround is removing the "@".

**Comment by paulstapor** [comment]
Okay, I see the problem. If it's possible by some nice simple trick, we'll leave it like that.
